CREATE DATABASE IF NOT EXISTS ioesems;
USE ioesems;

CREATE TABLE IF NOT EXISTS quotes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  quote_text TEXT NOT NULL,
  author VARCHAR(150) NOT NULL,
  date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
