CREATE DATABASE IF NOT EXISTS ioesems;
USE ioesems;

CREATE TABLE IF NOT EXISTS comments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  comment_text TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);
